### ISSUE TITLE
Mention trick to free up space on GitHub action

### ISSUE THREAD

**Issue by vrothberg** [nzwulfin/cicd-bootc#2]
Hey Matt,
I ran into the infamous "no space left on device" issue building my fedora-bootc-workstation image which brought me to https://github.com/orgs/community/discussions/25678.  Adding the following 1st step to my action resolved the issue for me (see https://github.com/vrothberg/fedora-bootc-workstation/pull/26/files):
```yml
    # https://github.com/orgs/community/discussions/25678
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
```

I believe that your repository will have quite some traffic going forward, so it may be worth mentioning that in the README or maybe even the blog.
